ADMIN_EMAIL: support@10khours.to
ADMIN_PASSWORD: password
POSTMARK_API_TOKEN: asdf-qwer-tyui # dont change this
PROJECT_NAME: Kulp Estates
TAGLINE: Tech entrepreneur learning to farm, raise livestock, and build a compound for experiential networking retreats.
DESCRIPTION: 10k Hours is a live changelog documenting my... (Raw HTML supported! Ex: <a href="#" class="text-brand-orange">link here</a>)
EXTERNAL_URL: https://twitter.com/ryanckulp
development:
  BASE_URL: http://localhost:3000 # dont change this
production:
  BASE_URL: https://your-custom-domain-here.com
